# === Python Modules ===
from pydantic import BaseModel, Field
from typing import Literal

# === Query Rewriter Schema ===
class QueryRewrite(BaseModel):
    """
    Schema for the output of the query rewriter agent.
    """
    rephrased_question: str = Field(
        description = "The rephrased question that is more specific and context-aware."
    )

    tool_flag: bool = Field(
        description = "Boolean flag to know whether to use Tool Node or not."
    )

# === Grading Documents ===
class DocGrader(BaseModel):
    """
    Schema for the output of the document grader agent.
    """
    score: Literal["Yes", "No"] = Field(
        description = "Document is relevant to the question? If yes -> 'Yes' if not -> 'No'"
    )

# === Answer Generation ===
class AnswerGeneration(BaseModel):
    """
    Schema for the output of the answer generation agent.
    """
    answer: str = Field(
        description = "The final user-facing answer generated by the model. Keep the length of the answer in 10-20 words maximum."
    )